# Generated by Django 3.2.20 on 2023-08-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='cpm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='wpm',
            field=models.FloatField(default=0.0),
        ),
    ]
